### PR TITLE
Add support for requestAnimationFrame

### PR DESCRIPTION
**Pull request by mAAdhaTTah**
I could really use a mocked `requestAnimationFrame` for some testing I'm doing, so I thought I'd take a crack at adding it here. I opted to just tick a rAF every 16ms, so the callbacks can just be run with `clock.tick(16)`. I think this mostly works / does what's needed, but I'm not sure of a few things, like bootstrapping this only in a browser or passing in the correct value for the callback arg. Let me know if I'm on the right track.

### CODE REVIEW

**Comment by mAAdhaTTah** [comment]
Added some tests to ensure callbacks are scheduled together in the next frame. Also added a `runToFrame` method to the clock to run the timer through the next frame. All of these have tests. If this looks like a good approach overall, I can add some docs.

Let me know what you think!

**Comment by mAAdhaTTah** [comment]
Updated from master after merge of #139.

**Comment by fatso83** [comment]
LGTM! Mind rebasing it instead of the merge :grimacing: ?

**Comment by mAAdhaTTah** [comment]
Sure! I'll add some docs too.

**Comment by mAAdhaTTah** [comment]
Alright, rebased, squashed, and updated the docs.

**Comment by fatso83** [comment]
Published as 2.2.0!

**Pull request merged**
