### PR TITLE
Implement clock.next()

### PR DESCRIPTION
**Pull request by novemberborn**
Rather than ticking by a certain number of milliseconds this method advanced the clock to the first scheduled timer. This is useful when performing fuzz testing on an entire application and you want to trigger a single timer.

I based the tests off of those for `clock.tick()`.

Let me know what you think! :smile:

### CODE REVIEW

**Comment by mroderick** [comment]
:+1:

**Comment by mroderick** [comment]
Needs a rebase, thanks to the listing branch getting merged

**Comment by novemberborn** [comment]
@mroderick rebased.

**Comment by fatso83** [comment]
[LGTM](http://lgtm.in/i/2ztJ60cgn)

[:+1:](http://lgtm.in/u/2ztJ60cgn)

**Comment by novemberborn** [comment]
:tada: thanks!

Any chance we can get a release out with this new feature? :smile:

**Comment by novemberborn** [comment]
> Any chance we can get a release out with this new feature?

@mroderick is this something you can do?

**Comment by mroderick** [comment]
Yep, just need to find a quiet spot in the airport

**Comment by novemberborn** [comment]
Cool! Safe travels :airplane:

**Comment by mroderick** [comment]
`v1.4.0` is tagged and on npm

**Pull request merged**
