### PR TITLE
Release/2.6.0

### PR DESCRIPTION
**Pull request by benjamingr**
Can you please make sure that I did this right before I `npm publish`? 

Also, I'm not sure I understood the step in https://github.com/sinonjs/lolex/blob/master/RELEASE.md#create-a-new-pr

Do I open a new PR (like this) and then merge it?

### CODE REVIEW

**Comment by fatso83** [comment]
Seems perfect! The 2.6.0 tag is now only in your repo, so I am not totally sure whether or now that automatically is brought over (would not think so), which in case you need to do that as a post-merge step.

Regarding the PR step I think we can skip it. I think I added it as a misunderstanding of how things worked, and recently I and Morgan have just done this locally in any case. The section could be dropped in a later PR :)

**Comment by benjamingr** [comment]
Got it, thanks!

**Comment by benjamingr** [comment]
@fatso83 hmm, looks like there is something problematic here, is this from my side?

```
~/Documents/OpenSource/lolex [release/2.6.0] $ npm publish

> lolex@2.6.0 prepublishOnly .
> npm run bundle


> lolex@2.6.0 bundle /Users/benjamin/Documents/OpenSource/lolex
> browserify -s lolex -o lolex.js src/lolex-src.js

npm ERR! publish Failed PUT 403
npm ERR! code E403
npm ERR! You do not have permission to publish "lolex". Are you logged in as the correct user? : lolex

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/benjamin/.npm/_logs/2018-05-16T08_50_47_666Z-debug.log
~/Documents/OpenSource/lolex [release/2.6.0] $ npm whoami
peer5
```

**Comment by fatso83** [comment]
Have you logged in? You need to do `npm login` first. And I think you might need to accept the invitation to the org.

**Comment by benjamingr** [comment]
@fatso83 the sinonjs org has the following packages https://www.npmjs.com/org/sinonjs (@sinonjs/formatio, @sinonjs/referee, @sinonjs/referee-sinon, @sinonjs/samsam ). 

It looks like lolex is published separately and outside of the org.

For example on referee [peer5 is a collaborator](https://www.npmjs.com/package/@sinonjs/referee) but [not on lolex](https://www.npmjs.com/package/lolex)

**Comment by fatso83** [comment]
Should be fixed now.

**Comment by fatso83** [comment]
dump
Should be fixed now.

**Comment by benjamingr** [comment]
Awesome :) 2.6.0 has been released.

Going to try adding the tag.

**Comment by benjamingr** [comment]
Tag is up. Let me know if there is anything else I need to do for this.

**Pull request merged**
