### PR TITLE
Add support for performance.now

### PR DESCRIPTION
**Pull request by benjamingr**
This pull request adds support (and tests) for `performance.now` in browser envrionments.

Fixes https://github.com/sinonjs/lolex/issues/82

### CODE REVIEW

**Comment by benjamingr** [comment]
Pinging @mroderick - let me know if you need anything from my side. We'd optimally like to get this merged pretty quickly since we need it for our own code base :)

**Comment by fatso83** [comment]
I'll look into this and the others today. New major version coming with lots of nice features.

**Comment by benjamingr** [comment]
@fatso83 sweet :) Thanks, would save us time

**Comment by benjamingr** [comment]
@fatso83 hey, any chance this could land today?

**Comment by fatso83** [comment]
Generally, if you need to distribute a fix in a open source package quickly to your team, fork the package and replace the dependency in package.json with something like this:

```diff
+   "lolex": "your-github-name/lolex",
-    "lolex": "1.5.1",
```

you can also pin the version down with commit-ish hashes like this:

```diff
+   "lolex": "your-github-name/lolex#my-performance-now-feature",
-    "lolex": "1.5.1",
```

That way you won't be held back by slow maintainers that are on holiday and need to do their code reviews on a smart phone ;-) That being said: I'll try to get this out today, but I was hoping to get another PR in I was waiting for a feedback on. Then again, it might come as the next minor version.

**Comment by benjamingr** [comment]
@fatso83 the problem with floating patches (I could just check out this branch in NPM) is that if it ends up being changed (or doesn't land) it means I have diverged and need to maintain the floating patch whenever the base library is updated.

I agree that this isn't super urgent - I'm just trying my luck in reducing my dependency complexity - as people have been doing to me in projects I work on (maybe just my OCD).

Anyway - thanks for landing :) LMK when you have a release.

**Comment by fatso83** [comment]
I was totally about to press the squash button now, when I realized that there is no mention of this feature in the docs. Care to push a commit with additions to `README.md`?

**Comment by benjamingr** [comment]
Sure @fatso83

**Comment by benjamingr** [comment]
@fatso83 updated, PTAL :)

**Comment by fatso83** [comment]
This has been published as `lolex@2.0.0`

**Comment by benjamingr** [comment]
Thanks for the quick feedback and response!

**Pull request merged**
