### PR TITLE
Use canonical name for changelog

### PR DESCRIPTION
**Pull request by paulmelnikow**
Thanks so much for this useful library – and for extracting it from sinon!

#### Purpose (TL;DR) - mandatory

Give the changelog its canonical name so tooling picks it up.

#### Background (Problem in detail)  - optional

- It's the name recommended by [Keep a Changelog](https://keepachangelog.com/en/1.0.0/).
- It's parsed automatically by tools like Dependabot and Greenkeeper.
- It's automatically included in `npm pack`.
- It's easier for developers to spot (see #216).

### CODE REVIEW

**Comment by benjamingr** [comment]
This looks very reasonable to me. Since it's what sinonjs/sinon does I'm going to go ahead and merge it.

Thank you for you contribution 🙏

**Comment by benjamingr** [comment]
For future reference the changelog is also referenced in the version build script at https://github.com/sinonjs/lolex/commit/53e32d410e3c0e6d18958b174394eb541d8aa71d

**Comment by paulmelnikow** [comment]
Thanks!

**Comment by fatso83** [comment]
I already did this three years ago, but it basically got rejected as I didn't have any proper reasons for it, other than "it seems right". Finally the planets have aligned! :heart:

**Pull request merged**
