### PR TITLE
Get global object properly

### PR DESCRIPTION
**Pull request by jedwards1211**
fix https://github.com/sinonjs/lolex/issues/71

### CODE REVIEW

**Comment by fatso83** [comment]
Thanks for the PR. Unfortunately it does not pass our tests. It specifically fails at the linting stage. Could you fix it and squash the resulting commits?

**Comment by jedwards1211** [comment]
@fatso83 what comment do I have to put to make jslint allow `new Function('return this')`?
Also, there are some issues in bitHound regarding code I didn't touch.

**Comment by fatso83** [comment]
@jedwards1211 Don't worry too much about BitHound right now. It does some linting that we cannot do anything with until we switch to eslint, as jslint is not supported with it. 

Regarding the eval error: I am not sure what you are talking about. I just ran `npm run lint` and got no errors. I even removed your jslint config comment and still got no errors.

```
npm run lint

> lolex@1.5.0 lint /Users/carl-erik.kopseng/dev-priv/lolex
> jslint src/**/*.js


src/lolex-src.js is OK.
```

Are you simply talking about BitHound, or are you getting some other results than me?

**Comment by jedwards1211** [comment]
Yeah, I was just talking about BitHound.

**Comment by fatso83** [comment]
Well, then just delete the comment, squash the commits, and it's good to go ☺️

**Comment by jedwards1211** [comment]
Okay, done!

**Comment by fatso83** [comment]
You still need to rebase your work off `master` as it is out-of-date and cannot be merged.

**Comment by fatso83** [comment]
I rebased it and merged it as 47b30ed

**Pull request closed without merging**
