### PR TITLE
bugfix for a setTimeout() or setSystemTime() within a nextTick() call.

### PR DESCRIPTION
**Pull request by rogierschouten**
```javascript
var lolex = require('lolex');

var clock = lolex.install({ 
	now: 0, 
	toFake: [
		"setTimeout", "clearTimeout", "setImmediate", "clearImmediate", "setInterval", "clearInterval", "Date", "nextTick"
	]
});

var callbackCalled = false;
process.nextTick(function() {
	setTimeout(function() {
			callbackCalled = true;
	}, 50);
});

// BUG: infinite loop!
while (!callbackCalled) {
	clock.tick(60); // note more than the delay of the setTimeout() call
}
```

### CODE REVIEW

**Comment by benjamingr** [comment]
Why did you delete the `package.lock` @rogierschouten?

**Comment by rogierschouten** [comment]
@benjamingr  Oh wait I thought I introduced the package-lock.json. I'll reintroduce it. 

But I just also found a second bug relating to this, and I'm losing track of how to fix this.

The clock.tick() function contains this code:
```
        runJobs(clock);
        clock.duringTick = false;
        updateHrTime(tickTo);
        clock.now = tickTo;
```

Notice how `clock.now` is only updated after the `runJobs()`.     I just created another setTimeout() within a nextTick() and it doesn't go off - because the statement `clock.now = tickTo` jumps right over the newly added timer time.

Let me chew for a moment on this

**Comment by rogierschouten** [comment]
@benjamingr  I think I have all the nextTick() related bugs now, I also added some tests that fail before my change and that are ok after my change. Hope this helps.

**Comment by benjamingr** [comment]
Basically, `runJobs` needs to happen at every two possible cases where timers get to run.

**Comment by rogierschouten** [comment]
Yes, and also, the local variables in `clock.tick()` need to remain compensated for any `setSystemTime()` calls that have come while running timers or jobs.

**Comment by rogierschouten** [comment]
Is this ok to get merged or do you need more from me?

**Comment by fatso83** [comment]
Squashing the changes cleaned up the history, so all good.

**Comment by fatso83** [comment]
2.3.1 released. :smile:

**Pull request merged**
