### PR TITLE
clearAnimationFrame is cancelAnimationFrame

### PR DESCRIPTION
**Pull request by SimenB**
Typo in the docs, implementation is correct

### CODE REVIEW

**Comment by benjamingr** [comment]
Worth mentioning to readers: this is just a docs change

**Comment by SimenB** [comment]
Yes, it's correct in the code. Only wrong in the readme

**Comment by fatso83** [comment]
Takker!

**Comment by SimenB** [comment]
Bare hyggelig! 🇳🇴

**Pull request merged**
