### PR TITLE
fix for issue #59

### PR DESCRIPTION
**Pull request by rogierschouten**

### CODE REVIEW

**Comment by fatso83** [comment]
I'll hold on merging this until we can get a test case from @gautaz. Would like to avoid reintroducing it :-)

P.S. Don't checking the compiled code. That keeps the diffs smaller and easier to look through. We only update the dist when publishing a new version.

**Comment by rogierschouten** [comment]
OK!

**Comment by rogierschouten** [comment]
@fatso83 test incorporated. It failed when I undid my fix and it passes now.

**Comment by fatso83** [comment]
Sorry for taking this long to merge this! Had to rebase so merged as #74.

**Pull request closed without merging**
